#!/bin/sh

overlay="$(dirname "$(realpath "$0")")/root"
program="PROGRAM"

dir="$(mktemp -d)"
mkdir -p "$dir/work"
rm -rf "$dir/work"
mkdir -p "$dir/work/bin"
mkdir -p "$dir/work/sbin"
mkdir -p "$dir/work/lib"
mkdir -p "$dir/work/usr"
mkdir -p "$dir/work/etc"
mkdir -p "$dir/work/var"
mkdir -p "$dir/work/opt"

mkdir -p "$dir/overlay/bin"
mkdir -p "$dir/overlay/sbin"
mkdir -p "$dir/overlay/lib"
mkdir -p "$dir/overlay/usr"
mkdir -p "$dir/overlay/etc"
mkdir -p "$dir/overlay/var"
mkdir -p "$dir/overlay/opt"

mount -t overlay overlay-usr -o "lowerdir=$overlay/usr:/usr,upperdir=$dir/overlay/usr,workdir=$dir/work/usr" /usr
mount -t overlay overlay-etc -o "lowerdir=$overlay/etc:/etc,upperdir=$dir/overlay/etc,workdir=$dir/work/etc" /etc
mount -t overlay overlay-var -o "lowerdir=$overlay/var:/var,upperdir=$dir/overlay/var,workdir=$dir/work/var" /var
mount -t overlay overlay-bin -o "lowerdir=$overlay/bin:/bin,upperdir=$dir/overlay/bin,workdir=$dir/work/bin" /bin
mount -t overlay overlay-lib -o "lowerdir=$overlay/lib:/lib,upperdir=$dir/overlay/lib,workdir=$dir/work/lib" /lib
mount -t overlay overlay-sbin -o "lowerdir=$overlay/sbin:/sbin,upperdir=$dir/overlay/sbin,workdir=$dir/work/sbin" /sbin
mount -t overlay overlay-opt -o "lowerdir=$overlay/opt:/opt,upperdir=$dir/overlay/opt,workdir=$dir/work/opt" /opt

"$program" "$@"
rm -rf "$dir"